### ISSUE TITLE
Client monitoring support

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar-quickstart#12]
Currently, there is no easy and documented way to enable [client monitoring](https://chainsafe.github.io/lodestar/usage/client-monitoring/). Possible option right now would be to add the CLI args to `LODESTAR_EXTRA_ARGS` but that's not ideal.

A possible solution would be that a user just has to provide the beaconcha.in API key similar to how [eth-docker does it](https://github.com/eth-educators/eth-docker/blob/a312e2d578adc906fac78b9e0825a126ae4d98aa/lodestar/docker-entrypoint.sh#L36) or maybe should in general support CL / VC extra args via script parameters (`--vcExtras`, `--clExtras`) which would allow more flexibility.

**Comment by nflaig** [comment]
@g11tech any thoughts on this?

**Comment by g11tech** [comment]
I guess we can , doesn't hurt to have

**Comment by nflaig** [comment]
> or maybe should in general support CL / VC extra args via script parameters (--vcExtras, --clExtras) which would allow more flexibility.

I would rather tend to just adding this, allows users to configure client monitoring and in general is useful feature
