### ISSUE TITLE
Bug in setup.sh with $validatorKeyArgs in line 316

### ISSUE THREAD

**Issue by dranol2021** [ChainSafe/lodestar-quickstart#13]
https://github.com/ChainSafe/lodestar-quickstart/blob/main/setup.sh
I am not quite sure, but I think there is a bug in the setup.sh script in line 316:

Instead of 
valCmd="$valCmd $LODESTAR_VALIDATOR_ARGS $validatorKeyArgs"
it should be
valCmd="$valCmd $LODESTAR_VALIDATOR_ARGS $LODESTAR_VALIDATOR_KEYSTORE_ARGS"

**Comment by g11tech** [comment]
hi @dranol2021 , `validatorKeyArgs` gets assigned here during validation 

https://github.com/ChainSafe/lodestar-quickstart/blob/main/validate.sh#L24:L38

closing right not, you may open it again if there is further any issue
thanks for trying out and looking into the scripts!
