### ISSUE TITLE
Add Reth to elClient

### ISSUE THREAD

**Issue by philknows** [ChainSafe/lodestar-quickstart#35]
We should add Reth here as its being actively used for testing and showing quite promising results with lodestar for Deneb+.

`docker pull ghcr.io/paradigmxyz/reth:v0.1.0-alpha.13` via https://paradigmxyz.github.io/reth/installation/docker.html

**Comment by g11tech** [comment]
yes, will add it, we also make sure other client combos are in working condition

**Comment by g11tech** [comment]
https://github.com/ChainSafe/lodestar-quickstart/pull/37
